FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /

COPY pyproject.toml /
COPY requirements.txt /app/
COPY /app/domain /app/domain
COPY /app/repositories /app/repositories
COPY /app/routers /app/routers
COPY /app/services /app/services
COPY /app/util /app/util
COPY /app/util/data_scrape/rabbit_mq_consumer.py /app
RUN pip install --upgrade pip
#    && pip install -r /app/requirements.txt \
RUN pip install poetry
RUN poetry install


CMD poetry shell && python -m app.rabbit_mq_consumer