FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /

COPY requirements.txt /app/
COPY /app/domain /app/domain
COPY /app/repositories /app/repositories
COPY /app/routers /app/routers
COPY /app/services /app/services
COPY /app/util /app/util
COPY /app/util/embeddings/rabbit_mq_consumer.py /app
RUN pip install --upgrade pip \
    && pip install -r /app/requirements.txt

CMD python -m app.rabbit_mq_consumer
