FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /

COPY pyproject.toml /
COPY requirements.txt /app/
COPY /app/domain /app/domain
COPY /app/repositories /app/repositories
COPY /app/routers /app/routers
COPY /app/services /app/services
COPY /app/util /app/util
RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry install
RUN rm -rf /app/util/embeddings


CMD poetry run python -m app.util.data_scrape.rabbit_mq_consumer
#CMD "tail -f /dev/null"