FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
COPY /domain /app/domain
COPY /repositories /app/repositories
COPY /routers /app/routers
COPY /services /app/services
COPY /util /app/util
COPY rabbit_mq_consumer.py /app
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

CMD ["python", "rabbit_mq_consumer.py"]