name: Test workflow

on:
  workflow_dispatch:
    inputs:
      var1:
        description: "var1"
        required: true
        default: lala
        options:
          - lala
      s3_key:
        description: "just a key"
        required: true


jobs:
  duhjob:
    runs-on: ubuntu-latest
    steps:
      - name: Add vars to vars file
        run: |
          echo "hiiii" >> hi.tt
          echo "s3_key = \"${{ inputs.var1 }}\"" >> hi.txt
          echo "partner = \"${{ inputs.s3_key }}\"" >> hi.txt
          cat hi.txt