name: Test workflow

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build_docker_continers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nardoarevalo14/openai_embeddings_service:latest


  duhjob:
    runs-on: ubuntu-latest
    steps:
      - name: Add vars to vars file
        run: |
          echo "hiiii" >> hi.tt
          echo "s3_key = \"${{ inputs.var1 }}\"" >> hi.txt
          echo "partner = \"${{ inputs.s3_key }}\"" >> hi.txt
          cat hi.txt