name: Test workflow

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build_docker_continers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Main Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nardoarevalo14/openai_embeddings_service:latest

      - name: Build and Push Datascrape Consumer Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-datascrape-rabbitmq-consumer
          push: true
          tags: nardoarevalo14/datascrape_consumer:latest

      - name: Build and Push Embeddings Consumer Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-embeddings-rabbitmq-consumer
          push: true
          tags: nardoarevalo14/embeddings_consumer:latest
